# Generated by Django 3.1.2 on 2021-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20201227_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='username',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
